name: My First Workflow
on: 
  push:
    branches: 
    - main
  workflow_dispatch:
jobs:
  MyFirstJob:
    runs-on: ubuntu-latest

    steps:
      - name: First Step
        run: echo "Hello world. This is my first github actions workflow."
