name: My First Workflow
on: 
  push:
    branches: 
    - main
  workflow_dispatch:
jobs:
  MyFirstJob:
    runs-on: ubuntu-latest

    steps:
      - name: First Step
        run: echo "Hello world. This is my first GitHub Actions workflow."

      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: List Files in the Repository
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"
  
  MySecondJob:
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        os_version: [ubuntu-latest]
        node_version: [22, 23, 24]
    name: My second job
    runs-on: ${{ matrix.os_version }}
      
    steps:
    - uses: actions/setup-node@v3.6.0
      with:
        node-version: ${{ matrix.node_version }}
         tree
