name: My First Workflow
on: 
  push:
    branches: 
    - main
  workflow_dispatch:
jobs:
  MyFirstJob:
    runs-on: ubuntu-latest
    name: My first job

    steps:
      - name: First Step
        run: echo "Hello world. This is my first GitHub Actions workflow."

      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: List Files in the Repository
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"

      - name: Set Color
        id: color-generator
        run: echo "SELECTED_COLOR=green" >> "$GITHUB_OUTPUT"

      - name: Get Color From Output
        run: echo "${{ steps.color-generator.output.SELECTED_COLOR }}"
  
  MySecondJob:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      max-parallel: 3
      matrix:
        node_version: [22, 23, 24]
    name: My second job
      
    steps:
    - uses: actions/setup-node@v3.6.0
      with:
        node-version: ${{ matrix.node_version }}
